"""Original paired English/Lithuanian physics lessons. CC BY-SA 4.0.
Run from physics-platform. Structured authoring data keeps mirrored item IDs and sequencing.
"""
from pathlib import Path
import yaml
P=Path('src/content/docs'); lang='en'; number=1

def t(en,lt):return lt if lang=='lt' else en

def block(kind,title,body,figure=None,mode=None):
 f=f' figure="{figure}" figureProps={{{{mode: "{mode}"}}}} alt="{t("Interactive ideal thermal model; the same values are listed in a data table.","Interaktyvus idealus šiluminis modelis; tos pačios reikšmės pateiktos duomenų lentelėje.")}"' if figure else ''
 return f'<Block kind="{kind}" title="{title}"{f}>\n\n{body}\n\n</Block>\n'

def frames(parts):return '<Frames>\n'+''.join(f'<Frame title="{title}">\n\n{body}\n\n</Frame>\n' for title,body in parts)+'</Frames>'

def hints(*texts):return '<Hints>\n'+''.join(f'<Hint>{h}</Hint>\n' for h in texts)+'</Hints>'

def choice(id,prompt,options,solution,outcome,tip=None,multi=False):
 s=f'<Choice id="g9-thermal-0{number}-{id}" outcome="{outcome}"'+(' multi' if multi else '')+'>\n\n'+prompt+'\n\n'
 for text,right,why in options:s+=f'<Option'+(' correct' if right else '')+f'>{text}<Why>{why}</Why></Option>\n'
 if tip:s+=hints(tip)+'\n'
 return s+f'<Solution>\n\n{solution}\n\n</Solution>\n</Choice>\n'

def numeric(id,prompt,answer,solution,outcome,wrong=None,tip=None,unit=None):
 s=f'<Numeric id="g9-thermal-0{number}-{id}" answer="{answer}" outcome="{outcome}"'+(f' unit="{unit}"' if unit else '')+'>\n\n'+prompt+'\n\n'
 for value,why in (wrong or []):s+=f'<Why value="{value}">{why}</Why>\n'
 if tip:s+=hints(tip)+'\n'
 return s+f'<Ok>{solution}</Ok>\n<Solution>\n\n{solution}\n\n</Solution>\n</Numeric>\n'

def quantity(id,prompt,expected,q,units,show,solution,outcome,wrong=None,tip=None,tolerance=.05):
 s=f'<Quantity id="g9-thermal-0{number}-{id}" expected={{{expected}}} quantity="{q}" units="{units}" show="{show}" tolerance={{{tolerance}}} outcome="{outcome}">\n\n{prompt}\n\n'
 for value,why in (wrong or []):s+=f'<Why value="{value}">{why}</Why>\n'
 if tip:s+=hints(tip)+'\n'
 return s+f'<Ok>{solution}</Ok>\n<Solution>\n\n{solution}\n\n</Solution>\n</Quantity>\n'

def example(title,steps,fade=0):return f'<Example title="{title}" fade={{{fade}}}>\n\n'+''.join(f'<ExStep>\n\n{s}\n\n</ExStep>\n' for s in steps)+'</Example>\n'

def turn(body):return '<YourTurn>\n\n'+body+'\n</YourTurn>\n'

def task(id,prompt,marks,solution,outcome):return f'<Task id="g9-thermal-0{number}-{id}" outcome="{outcome}">\n\n{prompt}\n\n<Marks>\n'+''.join(f'<Mark pts={{1}}>{m}</Mark>\n' for m in marks)+f'</Marks>\n<Solution>\n\n{solution}\n\n</Solution>\n</Task>\n'

objectives=[
[('I can distinguish temperature, internal energy and heat.','Moku atskirti temperatūrą, vidinę energiją ir šilumos kiekį.'),('I can explain two ways of changing internal energy.','Moku paaiškinti du vidinės energijos kitimo būdus.'),('I can compare temperature readings and temperature changes in °C and K.','Moku palyginti temperatūras ir jų pokyčius Celsijaus ir Kelvino skalėse.')],
[('I can apply Q = mcΔT with mass in kilograms and explain its limits.','Moku taikyti Q = mcΔT, masę nurodyti kilogramais ir paaiškinti modelio ribas.'),('I can read and draw a temperature–time graph with units.','Moku skaityti ir braižyti temperatūros ir laiko grafiką, nurodyti vienetus.'),('I can use specific heat capacity to compare heating and cooling.','Moku taikyti savitąją šilumą šildymui ir vėsimui palyginti.')],
[('I can plan a supervised investigation with a defined system and safe procedure.','Moku suplanuoti prižiūrimą tyrimą, apibrėžti sistemą ir saugią eigą.'),('I can record masses, temperatures and instrument resolution without inventing data.','Moku užrašyti mases, temperatūras ir prietaisų padalos vertę, neišgalvoti duomenų.'),('I can explain how timing and the container affect a mixing experiment.','Moku paaiškinti laiko ir indo įtaką vandens maišymo tyrimui.')],
[('I can calculate an ideal mixing temperature and state the assumptions.','Moku apskaičiuoti idealią mišinio temperatūrą ir nurodyti prielaidas.'),('I can calculate heat gained and lost from measured or labelled model data.','Moku apskaičiuoti gautą ir atiduotą šilumos kiekį iš matavimų arba aiškiai pažymėtų modelio duomenų.'),('I can use a discrepancy as evidence about the model, without claiming energy disappeared.','Moku skirtumą susieti su modelio ribomis, neteigti, kad energija išnyko.')]]

slugs=['temperature-energy-heat','specific-heat-and-graphs','water-mixing-investigation','heat-balance']
titles=[('Temperature, internal energy and heat','Temperatūra, vidinė energija ir šiluma'),('Heat, specific heat capacity and graphs','Šilumos kiekis, savitoji šiluma ir grafikai'),('Investigating water mixing','Vandens maišymo tyrimas'),('Heat balance: from model to evidence','Šilumos balansas: nuo modelio iki įrodymų')]

def lesson1():
 o=[f'g9.thermal.{i}' for i in range(1,4)]; b=[]
 b.append(block('remember',t('Read a quantity before explaining it','Pirma perskaityk dydį'),
 numeric('r1',t('A thermometer reads 18 °C, then 23 °C. How much did the temperature rise? Enter the number; the unit is shown.','Termometras rodė 18 °C, vėliau 23 °C. Kiek pakilo temperatūra? Įrašyk skaičių; vienetas nurodytas.'),'5',t('23 − 18 = 5. This is a change, not the final reading.','23 − 18 = 5. Tai pokytis, ne galutinė temperatūra.'),o[2],wrong=[('23',t('23 is the final reading. Subtract the initial reading.','23 yra galutinė temperatūra. Atimk pradinę.'))],unit='K')+
 numeric('r2',t('A cup contains 250 g of water. Write its mass in kilograms.','Puodelyje yra 250 g vandens. Nurodyk masę kilogramais.'),'0.25',t('1000 g = 1 kg, so 250 g = 0.25 kg.','1000 g = 1 kg, todėl 250 g = 0,25 kg.'),o[0],wrong=[('250',t('Divide grams by 1000 to obtain kilograms.','Gramų skaičių dalyk iš 1000.'))],unit='kg')+
 t('**Quick refresh.** Particles of a liquid move continually and interact. They do not start moving only when we heat it. A temperature reading describes the thermal state; write the quantity and its unit together.','**Trumpas prisiminimas.** Skysčio dalelės nuolat juda ir sąveikauja. Jos nepradeda judėti tik pašildžius skystį. Temperatūra apibūdina šiluminę būseną; dydį rašyk su vienetu.')))
 b.append(block('hook',t('Same thermometer reading, same energy?','Ta pati temperatūra – ta pati energija?'),
 t('A cup and a bucket both contain water at 20 °C. Your friend says: “The thermometer readings are equal, so their internal energies must be equal.” Before reading on, write whether the conclusion follows and name one missing fact.','Puodelyje ir kibire yra 20 °C vanduo. Draugas sako: „Termometrų rodmenys vienodi, todėl jų vidinės energijos vienodos.“ Prieš skaitydamas toliau parašyk, ar išvada pagrįsta, ir kokio fakto trūksta.')+
 choice('h1',t('What does the equal reading establish?','Ką rodo vienodos temperatūros?'),[(t('The water has the same temperature.','Vandens temperatūra vienoda.'),True,t('It establishes the thermal state, not equality of the total energy stored in two different amounts of water.','Jos nusako šiluminę būseną, bet ne dviejų skirtingų vandens kiekių visos vidinės energijos lygybę.')),(t('Both samples have the same internal energy.','Abiejų vandens kiekių vidinė energija vienoda.'),False,t('The amount of water matters too. Temperature alone is insufficient.','Svarbus ir vandens kiekis. Vien temperatūros nepakanka.')),(t('No particles are moving.','Dalelės nejuda.'),False,t('Liquid water has thermal motion at 20 °C.','20 °C skystame vandenyje vyksta šiluminis judėjimas.'))],t('Only equality of temperature follows. To compare energy changes, we will need the masses and material too.','Galime teigti tik temperatūrų lygybę. Energijos pokyčiams palyginti reikės masės ir medžiagos.'),o[0])))
 b.append(block('explain',t('Three ideas, three different questions','Trys sąvokos – trys klausimai'),frames([
 (t('Temperature: how warm?','Temperatūra: kiek šilta?'),t('Temperature describes the thermal state. In the particle model, for the same liquid, a higher temperature is associated with more intense thermal motion. A thermometer measures temperature after it approaches thermal equilibrium with the object. Touch is unreliable: metal and wood in the same room may feel different because they transfer energy to your hand at different rates.','Temperatūra apibūdina kūno šiluminę būseną. Dalelių modelyje to paties skysčio aukštesnė temperatūra siejama su intensyvesniu šiluminiu judėjimu. Termometras matuoja temperatūrą, artėdamas prie šiluminės pusiausvyros su kūnu. Lytėjimas nepatikimas: tame pačiame kambaryje metalas ir mediena gali atrodyti skirtingai šalti, nes nevienodai greitai perduoda energiją rankai.')),
 (t('Internal energy: what is stored?','Vidinė energija: kas sukaupta?'),t('Internal energy includes the energy of the particles’ microscopic motion and interactions. It is a property of the system we choose, for example all the water in the cup. It is not the energy of the whole cup moving across a table. Mass, material, temperature and state all matter; a thermometer is not a meter of total internal energy.','Vidinę energiją sudaro dalelių mikroskopinio judėjimo ir sąveikos energija. Tai pasirinktos sistemos, pavyzdžiui, viso vandens puodelyje, savybė. Ji nėra viso puodelio judėjimo stalu energija. Svarbūs masė, medžiaga, temperatūra ir būsena; termometras nematuoja visos vidinės energijos.')),
 (t('Heat: what crosses the boundary?','Šiluma: kas perduodama?'),t('Heat is energy transferred because of a temperature difference. We use $Q$ for the transferred amount and measure it in joules (J). If warm and cool water exchange energy without external work, net heat flows from the warmer part towards the cooler part until equilibrium. Say “the water received heat”, rather than “the water contains heat”. Internal energy is stored; heat describes transfer.','Šiluma yra energijos perdavimas dėl temperatūrų skirtumo. Perduotą šilumos kiekį žymime $Q$ ir matuojame džauliais (J). Kai šiltas ir vėsus vanduo keičiasi energija be išorinio darbo, grynasis šilumos perdavimas vyksta iš šiltesnio į vėsesnį iki pusiausvyros. Tiksliau sakyti „vanduo gavo šilumos“, o ne „vandenyje yra šilumos“. Vidinė energija sukaupta, o šiluma apibūdina perdavimą.')),
 (t('Two ways to change internal energy','Du vidinės energijos kitimo būdai'),t('Internal energy can change through heat transfer **or work**. A warm radiator transfers energy to cooler surroundings. Rubbing your hands or stirring a liquid with a paddle transfers energy by work. These processes can occur together: define the system and explain which transfer you are discussing.','Vidinė energija gali kisti perduodant šilumą **arba atliekant darbą**. Šiltas radiatorius perduoda šilumą vėsesnei aplinkai. Trinant rankas arba maišant skystį mentele energija perduodama darbu. Abu procesai gali vykti kartu: apibrėžk sistemą ir paaiškink, apie kurį perdavimą kalbi.'))])))
 b.append(block('explore',t('Two scales, one temperature','Dvi skalės, viena temperatūra'),
 t('Predict first: does converting 20 °C to kelvins describe hotter water? Select another reading and compare the table.\n\n$$T(\\mathrm{K})=t(^{\\circ}\\mathrm{C})+273.15.$$\n\nA rise from 20 °C to 30 °C is **10 °C = 10 K as a change**. The final temperature is **303.15 K**, not 10 K. Kelvin uses no degree symbol. For this introductory lesson, 273.15 is the scale offset, not a measure of energy.','Pirmiausia numatyk: ar 20 °C perskaičiavimas į kelvinus reiškia, kad vanduo sušilo? Pasirink kitą temperatūrą ir palygink lentelę.\n\n$$T(\\mathrm{K})=t(^{\\circ}\\mathrm{C})+273{,}15.$$\n\nPakilus nuo 20 °C iki 30 °C, **pokytis yra 10 °C = 10 K**. Galutinė temperatūra yra **303,15 K**, ne 10 K. Kelvino vienetas rašomas be laipsnio ženklo. Šioje įvadinėje pamokoje 273,15 yra skalių poslinkis, ne energijos matas.'),'thermal-model','scales'))
 b.append(block('examples',t('Explain a situation, then try a new one','Paaiškink situaciją ir pabandyk pats'),
 example(t('Example 1 · A spoon in warm water','1 pavyzdys · Šaukštas šiltame vandenyje'),[t('Choose the spoon as the system. Initially the water is warmer than the spoon.','Sistema – šaukštas. Iš pradžių vanduo šiltesnis už šaukštą.'),t('Energy crosses into the spoon because of that temperature difference: heat transfer increases its internal energy. Its temperature rises towards equilibrium.','Dėl temperatūrų skirtumo energija perduodama šaukštui šiluma: jo vidinė energija didėja. Temperatūra kyla, artėdama prie pusiausvyros.')])+
 turn(choice('p1',t('A room-temperature spoon is placed in cooler water. Which description fits the spoon?','Kambario temperatūros šaukštas įdedamas į vėsesnį vandenį. Kas vyksta šaukštui?'),[(t('It gives heat to the water; its internal energy decreases.','Jis atiduoda šilumą vandeniui; jo vidinė energija mažėja.'),True,t('The direction reverses because the spoon is initially warmer.','Kryptis pasikeičia, nes iš pradžių šaukštas šiltesnis.')),(t('Cold flows into the spoon.','Šaltis teka į šaukštą.'),False,t('Describe energy transfer from warm to cool, rather than a flow of “cold”.','Apibūdink energijos perdavimą iš šiltesnio į vėsesnį, ne „šalčio tekėjimą“.'))],t('The spoon transfers heat to the cooler water and cools.','Šaukštas atiduoda šilumą vėsesniam vandeniui ir vėsta.'),o[1]))+
 example(t('Example 2 · Rubbing hands','2 pavyzdys · Rankų trynimas'),[t('Choose both hands as the system. You use muscles to rub them together.','Sistema – abi rankos. Raumenimis jas trini vieną į kitą.'),t('Work changes their internal energy. A temperature rise is evidence of a change, but it does not mean the energy must have arrived as heat.','Darbas keičia jų vidinę energiją. Temperatūros kilimas rodo pokytį, bet neįrodo, kad energija būtinai perduota šiluma.')],1)+
 turn(choice('p2',t('A paddle driven by a motor stirs water in an insulated container. Which transfer is intended?','Variklis suka mentelę ir maišo vandenį izoliuotame inde. Koks energijos perdavimas numatytas?'),[(t('Work on the water.','Darbas vandeniui.'),True,t('The paddle does work; the insulation is intended to reduce heat exchange with surroundings.','Mentelė atlieka darbą; izoliacija mažina šilumos mainus su aplinka.')),(t('Heat from a hotter outside body.','Šiluma iš karštesnio išorinio kūno.'),False,t('No hotter external body is specified. A mechanical paddle supplies work.','Karštesnis išorinis kūnas nenurodytas. Mentelė perduoda energiją darbu.'))],t('Work can increase internal energy even when heat exchange is small.','Darbas gali didinti vidinę energiją net esant mažiems šilumos mainams.'),o[1]))+
 example(t('Example 3 · A reading and a change','3 pavyzdys · Temperatūra ir pokytis'),[t('Convert 25 °C: 25 + 273.15 = 298.15 K.','Perskaičiuok 25 °C: 25 + 273,15 = 298,15 K.'),t('For cooling from 25 °C to 18 °C, ΔT = 18 − 25 = −7 K. The scale offset cancels in a difference.','Vėstant nuo 25 °C iki 18 °C, ΔT = 18 − 25 = −7 K. Skalių poslinkis skirtume susiprastina.')],1)+
 turn(quantity('p3',t('Convert a final reading of 30 °C to kelvins.','Galutinę 30 °C temperatūrą perskaičiuok į kelvinus.'),303.15,'absolute-temperature','K','303.15 K' if lang=='en' else '303,15 K',t('30 + 273.15 = 303.15 K.','30 + 273,15 = 303,15 K.'),o[2],wrong=[('30',t('30 is the Celsius reading. Add the scale offset for an absolute kelvin temperature.','30 yra Celsijaus temperatūra. Absoliučiai temperatūrai kelvinais pridėk skalių poslinkį.'))]))))
 b.append(block('check',t('Check the distinctions','Pasitikrink sąvokas'),t('Try all five. The first four are the core; the fifth is a written explanation. Feedback is for practice, not a school mark.','Atlik visas penkias užduotis. Pirmosios keturios yra pagrindinės; penktoje paaiškink raštu. Grįžtamasis ryšys skirtas mokytis, ne mokykliniam pažymiui.')+
 choice('c1',t('Which quantity is measured in joules?','Kuris dydis matuojamas džauliais?'),[(t('Heat transferred.','Perduotas šilumos kiekis.'),True,t('Heat is an amount of transferred energy.','Šilumos kiekis – perduotos energijos kiekis.')),(t('Temperature.','Temperatūra.'),False,t('Temperature is measured in °C or K.','Temperatūra matuojama °C arba K.'))],t('Q is measured in J. Temperature and energy are different quantities.','Q matuojamas J. Temperatūra ir energija – skirtingi dydžiai.'),o[0])+
 choice('c2',t('Two unequal masses of the same liquid have the same temperature. What can you conclude from the temperature alone?','Dviejų nevienodų to paties skysčio masių temperatūra vienoda. Ką gali nuspręsti vien iš temperatūros?'),[(t('Their total internal energies cannot be compared from that reading alone.','Vien šio rodmens nepakanka visai vidinei energijai palyginti.'),True,t('Amount and material are part of the comparison.','Palyginimui svarbus kiekis ir medžiaga.')),(t('Their total internal energies must be equal.','Jų visa vidinė energija būtinai vienoda.'),False,t('Equal temperature does not erase the difference in the amounts of liquid.','Vienoda temperatūra nepanaikina skysčio kiekio skirtumo.'))],t('Equal thermal state is not a guarantee of equal total internal energy.','Vienoda šiluminė būsena negarantuoja vienodos visos vidinės energijos.'),o[0])+
 choice('c3',t('A hot mug cools on a table. Which description identifies the main transfer out of the mug?','Karštas puodelis vėsta ant stalo. Kaip apibūdinsi pagrindinį energijos perdavimą iš puodelio?'),[(t('Heat transfer to cooler surroundings.','Šilumos perdavimas vėsesnei aplinkai.'),True,t('The temperature difference drives transfer.','Perdavimą lemia temperatūrų skirtumas.')),(t('Only work, because its temperature changed.','Tik darbas, nes temperatūra pasikeitė.'),False,t('A temperature change does not by itself identify work. Here cooler surroundings are specified.','Vien temperatūros pokytis nereiškia darbo. Čia nurodyta vėsesnė aplinka.'))],t('Choose the mug as the system: it gives energy to cooler surroundings by heat transfer.','Sistema – puodelis: jis šiluma perduoda energiją vėsesnei aplinkai.'),o[1])+
 quantity('c4',t('Water cools from 40 °C to 32 °C. Give signed ΔT = final − initial.','Vanduo vėsta nuo 40 °C iki 32 °C. Nurodyk ΔT = galutinė − pradinė su ženklu.'),-8,'temperature-difference','K|°C','−8 K',t('32 − 40 = −8; the difference has the same value in K and °C.','32 − 40 = −8; pokytis kelvinais ir Celsijaus laipsniais turi tą pačią skaitinę reikšmę.'),o[2],wrong=[('8',t('You gave the magnitude. The defined final-minus-initial change is negative.','Nurodei pokyčio modulį. Pagal galutinė minus pradinė sutartį pokytis neigiamas.'))])+
 task('c5',t('Write two sentences correcting: “Rubbing my hands adds heat stored in them, and doubling their temperature doubles their internal energy.” Identify the transfer and explain the missing information.','Dviem sakiniais pataisyk: „Trindamas rankas pridedu jose sukauptos šilumos, o padvigubėjus temperatūrai vidinė energija padvigubėja.“ Nurodyk perdavimo būdą ir paaiškink, kokios informacijos trūksta.'),[t('Identify work as the transfer from rubbing.','Nurodytas darbas trinant rankas.'),t('Distinguish stored internal energy from heat transfer.','Atskirta sukaupta vidinė energija ir šilumos perdavimas.'),t('Reject a general proportionality based only on a temperature reading.','Atmestas bendras proporcingumas vien pagal temperatūrą.')],t('Rubbing transfers energy by work, increasing the hands’ internal energy; heat is not something “stored” in them. A temperature reading alone does not determine total internal energy, and doubling a Celsius reading is not physically doubling absolute temperature. Even in kelvin, proportionality is not a general rule for arbitrary systems; it needs a specific model.','Trinant energija perduodama darbu ir didina rankų vidinę energiją; „sukaupta šiluma“ nėra tikslus apibūdinimas. Vien temperatūra nenusako visos vidinės energijos, o dvigubas Celsijaus rodmuo nėra dviguba absoliuti temperatūra. Net kelvinais proporcingumas nėra bendras bet kurios sistemos dėsnis; jam reikia konkretaus modelio.'),o[0])))
 b.append(block('summary',t('Keep the question attached to the quantity','Susiek dydį su jo klausimu'),t('**Temperature:** thermal state, °C or K. **Internal energy:** microscopic energy of the chosen system, J. **Heat:** energy transfer due to a temperature difference, J. Internal energy changes by heat transfer or work. A temperature difference of 1 °C equals 1 K; an absolute temperature needs the scale offset.','**Temperatūra:** šiluminė būsena, °C arba K. **Vidinė energija:** pasirinktos sistemos mikroskopinė energija, J. **Šiluma:** energijos perdavimas dėl temperatūrų skirtumo, J. Vidinė energija kinta perduodant šilumą arba atliekant darbą. 1 °C pokytis lygus 1 K; absoliučiai temperatūrai reikia skalių poslinkio.')+'\n\n<Next>'+t('How much energy must we transfer to warm a given mass of water?','Kiek energijos reikia perduoti tam tikrai vandens masei pašildyti?')+'</Next>'))
 b.append(block('teacher',t('Teaching notes and a 45-minute route','Pastabos mokytojui ir 45 min eiga'),t('**Core route:** recall 4 min; cup/bucket prediction 5; explanation and scale model 10; examples 10; checks 11; exit explanation 5. Use the written challenge as an extension if discussion runs long. Timing has not been trialled in class.\n\n**Respond to misconceptions:** ask “what is our system?” before naming a transfer. Use the equal-temperature cup/bucket as a counterexample to reading total energy from a thermometer. Do not introduce a general equation linking total internal energy to Celsius temperature.\n\n**Terminology EN · LT:** temperature · temperatūra; internal energy · vidinė energija; heat transferred · šilumos kiekis; thermal motion · šiluminis judėjimas; work · darbas; thermal equilibrium · šiluminė pusiausvyra.\n\n**Scope:** the internal-energy programme node is partly addressed. Changes of state and detailed microscopic models are not completed here. Physics, Lithuanian terminology and classroom review are pending; this is original trial material, not a teacher-certified lesson.','**Pagrindinė eiga:** prisiminimas 4 min; puodelio ir kibiro prognozė 5; aiškinimas ir skalių modelis 10; pavyzdžiai 10; pasitikrinimas 11; baigiamasis paaiškinimas 5. Jei diskusija užtrunka, rašytinę užduotį skirk papildomai. Laikas klasėje dar neišbandytas.\n\n**Klaidų aptarimas:** prieš įvardydami perdavimą klauskite „kokia mūsų sistema?“ Vienodos temperatūros puodelis ir kibiras padeda paneigti visos energijos nustatymą termometru. Neteikite bendros visos vidinės energijos priklausomybės nuo Celsijaus temperatūros lygties.\n\n**Terminai EN · LT:** temperature · temperatūra; internal energy · vidinė energija; heat transferred · šilumos kiekis; thermal motion · šiluminis judėjimas; work · darbas; thermal equilibrium · šiluminė pusiausvyra.\n\n**Aprėptis:** vidinės energijos programos tema aptarta iš dalies. Būsenų kitimas ir išsamūs mikroskopiniai modeliai čia neužbaigti. Fizikos, lietuviškų terminų ir darbo klasėje žmogaus peržiūra dar neatlikta; tai originali bandomoji medžiaga.')))
 return ''.join(b)

def lesson2():
 o=[f'g9.thermal.{i}' for i in range(4,7)];b=[]
 b.append(block('remember',t('Mass, change and transfer','Masė, pokytis ir perdavimas'),
 numeric('r1',t('Convert 200 g of water to kilograms.','200 g vandens masę perskaičiuok į kilogramus.'),'0.2',t('200 ÷ 1000 = 0.20 kg.','200 ÷ 1000 = 0,20 kg.'),o[0],wrong=[('200',t('Use kilograms, not the original gram value.','Naudok kilogramus, ne pradinį gramų skaičių.'))],unit='kg')+
 quantity('r2',t('Water warms from 20 °C to 30 °C. Give its temperature change.','Vanduo šyla nuo 20 °C iki 30 °C. Nurodyk temperatūros pokytį.'),10,'temperature-difference','K|°C','10 K',t('30 − 20 = 10 K, also a change of 10 °C.','30 − 20 = 10 K, taip pat 10 °C pokytis.'),o[0],wrong=[('30',t('Subtract the initial temperature; do not use the final reading.','Atimk pradinę temperatūrą; nenaudok vien galutinio rodmens.'))])+
 t('**Bridge from lesson 1.** Heat transferred is measured in J. Internal energy belongs to the chosen system. We now model the water while it remains liquid; the container is outside this simple calculation.','**Ryšys su 1 pamoka.** Šilumos kiekis matuojamas J. Vidinė energija yra pasirinktos sistemos savybė. Dabar modeliuojame skystą vandenį; indo energijos į šį paprastą skaičiavimą neįtraukiame.')))
 b.append(block('hook',t('Which cup takes more energy?','Kuriam puodeliui reikia daugiau energijos?'),choice('h1',t('We warm 0.10 kg and 0.20 kg of water from 20 °C to 30 °C. Both stay liquid. Predict the energy comparison.','0,10 kg ir 0,20 kg vandens pašildome nuo 20 °C iki 30 °C. Abiem atvejais vanduo lieka skystas. Palygink reikalingą energiją.'),[(t('The 0.20 kg sample requires twice as much.','0,20 kg vandeniui reikia dvigubai daugiau.'),True,t('With the same material and temperature rise, the required energy is proportional to mass.','Tai pačiai medžiagai ir tam pačiam pokyčiui energija proporcinga masei.')),(t('Both require the same, because the final temperatures match.','Abiem reikia tiek pat, nes galutinė temperatūra vienoda.'),False,t('Temperature alone leaves out the amount of water.','Vien temperatūra neatsižvelgia į vandens kiekį.')),(t('The smaller mass requires twice as much.','Mažesnei masei reikia dvigubai daugiau.'),False,t('Less water requires less transferred energy for the same temperature rise.','Mažesniam vandens kiekiui tokiam pačiam pokyčiui reikia mažiau energijos.'))],t('Doubling mass doubles Q when c and ΔT stay the same. Check this after the explanation.','Padvigubinus masę, Q padvigubėja, kai c ir ΔT tie patys. Po paaiškinimo patikrink.'),o[2])))
 b.append(block('explain',t('Build the model with units','Sudaryk modelį su vienetais'),frames([
 (t('What specific heat capacity means','Ką reiškia savitoji šiluma'),t('Specific heat capacity $c$ is the heat needed to raise 1 kg of a material by 1 K without a change of state. Different materials have different values. For our liquid-water model, use $c=4200\\ \\mathrm{J/(kg\\cdot K)}$. This is a useful approximation for these modest temperature ranges, not a universal constant for every state or temperature. For a temperature difference, J/(kg·K) and J/(kg·°C) are equivalent units.','Savitoji šiluma (savitoji šiluminė talpa) $c$ nurodo šilumos kiekį, reikalingą 1 kg medžiagos temperatūrai pakelti 1 K nekintant būsenai. Skirtingų medžiagų ji skirtinga. Šio skysto vandens modelyje naudojame $c=4200\\ \\mathrm{J/(kg\\cdot K)}$. Tai tinkamas artinys nedideliam temperatūrų intervalui, ne universali visų būsenų ir temperatūrų konstanta. Temperatūros pokyčiui J/(kg·K) ir J/(kg·°C) yra lygiaverčiai vienetai.')),
 (t('The calculation','Skaičiavimas'),t('For unchanged state and approximately constant $c$,\n\n$$Q=mc\\Delta T,\\qquad \\Delta T=T_f-T_i.$$\n\nHere $Q$ is **positive when the water gains energy as heat**. Put mass in kg. A difference may be in K or °C because the steps have the same size. The unit check is $\\mathrm{kg}\\times\\mathrm{J/(kg\\cdot K)}\\times\\mathrm{K}=\\mathrm{J}$.','Kai būsena nekinta ir $c$ laikome pastovia,\n\n$$Q=mc\\Delta T,\\qquad \\Delta T=T_f-T_i.$$\n\nČia $Q$ **teigiamas, kai vanduo gauna energijos šiluma**. Masę nurodyk kg. Pokytis gali būti K arba °C, nes jų padalos vienodo dydžio. Vienetų patikra: $\\mathrm{kg}\\times\\mathrm{J/(kg\\cdot K)}\\times\\mathrm{K}=\\mathrm{J}$.')),
 (t('Cooling and the model boundary','Vėsimas ir modelio ribos'),t('For cooling, final − initial is negative, so the signed heat transfer to the water is negative. The **magnitude of heat given away** is its positive opposite. State which quantity you report.\n\nDo not use $mc\\Delta T$ to describe melting at constant temperature: energy can change the state even while ΔT is zero. We will treat phase changes later. Real heating can also warm the container and surroundings; energy supplied by a heater need not all reach the water.','Vėstant galutinė minus pradinė temperatūra neigiama, todėl šilumos kiekis vandeniui su ženklu taip pat neigiamas. **Atiduoto šilumos kiekio modulis** yra teigiamas priešingo ženklo dydis. Nurodyk, ką pateiki.\n\nLydymosi esant pastoviai temperatūrai neaprašyk $mc\\Delta T$: energija gali keisti būseną, nors ΔT lygu nuliui. Fazinius virsmus nagrinėsime vėliau. Tikras šildymas šildo ir indą bei aplinką; ne visa šildytuvo energija būtinai tenka vandeniui.'))])))
 b.append(block('explore',t('Predict the slope, then change the mass','Numatyk nuolydį, tada pakeisk masę'),t('**Illustrative model data, not measurements.** A constant 42 W transfers 42 J every second to the water. Start with 0.20 kg at 20 °C; ignore the container and heat loss. At 0, 50, 100, 150 and 200 s, the temperatures are 20, 22.5, 25, 27.5 and 30 °C.\n\nDraw the graph on paper: horizontal axis $t$ in s, vertical axis $T$ in °C. The slope is **temperature rise per second**, not heat itself. Predict what doubling mass does, then select 0.40 kg. What changes? What stays the same? Explain using $Q=mc\\Delta T$.','**Iliustraciniai modelio duomenys, ne matavimai.** Pastovi 42 W galia kiekvieną sekundę perduoda vandeniui 42 J. Pradžioje 0,20 kg vandens temperatūra 20 °C; indo ir nuostolių nepaisoma. Po 0, 50, 100, 150 ir 200 s temperatūra yra 20; 22,5; 25; 27,5 ir 30 °C.\n\nNubraižyk grafiką popieriuje: horizontalioji ašis $t$ sekundėmis, vertikalioji $T$ Celsijaus laipsniais. Nuolydis yra **temperatūros pokytis per sekundę**, ne pati šiluma. Numatyk, ką pakeis dviguba masė, tada pasirink 0,40 kg. Kas kinta, kas lieka taip pat? Paaiškink taikydamas $Q=mc\\Delta T$.'),'thermal-model','heating'))
 b.append(block('examples',t('Calculate, reverse, compare','Apskaičiuok, rask kitą dydį, palygink'),
 example(t('Example 1 · Heating water','1 pavyzdys · Vandens šildymas'),[t('For 200 g warming from 20 °C to 30 °C: m = 0.20 kg; ΔT = 10 K.','200 g vandens šyla nuo 20 °C iki 30 °C: m = 0,20 kg; ΔT = 10 K.'),t('$Q=0.20\\times4200\\times10=8400\\ \\mathrm{J}=8.4\\ \\mathrm{kJ}$. Positive: the water gains energy.','$Q=0{,}20\\times4200\\times10=8400\\ \\mathrm{J}=8{,}4\\ \\mathrm{kJ}$. Teigiamas: vanduo gauna energijos.')])+
 turn(quantity('p1',t('Warm 0.40 kg of water by 10 K. How much heat is received?','0,40 kg vandens pašildoma 10 K. Kiek šilumos gaunama?'),16800,'energy-transfer','J|kJ',t('16 800 J = 16.8 kJ','16 800 J = 16,8 kJ'),t('0.40 × 4200 × 10 = 16 800 J; twice example 1.','0,40 × 4200 × 10 = 16 800 J; dvigubai daugiau nei 1 pavyzdyje.'),o[0],wrong=[('8400',t('The temperature rise matches, but the mass has doubled.','Pokytis tas pats, bet masė dviguba.'))],tip=t('Use 0.40 kg, not 400 g, in the formula.','Į formulę įrašyk 0,40 kg, ne 400 g.')))+
 example(t('Example 2 · Find the temperature rise','2 pavyzdys · Rask temperatūros pokytį'),[t('0.10 kg of water receives 2100 J. Rearrange: $\\Delta T=Q/(mc)$.','0,10 kg vandens gauna 2100 J. Pertvarkyk: $\\Delta T=Q/(mc)$.'),t('$\\Delta T=2100/(0.10\\times4200)=5\\ \\mathrm{K}$. If it started at 20 °C, its final temperature is 25 °C.','$\\Delta T=2100/(0{,}10\\times4200)=5\\ \\mathrm{K}$. Jei pradžioje buvo 20 °C, galutinė temperatūra 25 °C.')],1)+
 turn(quantity('p2',t('0.20 kg of water receives 4200 J. Find ΔT.','0,20 kg vandens gauna 4200 J. Rask ΔT.'),5,'temperature-difference','K|°C','5 K',t('4200/(0.20 × 4200) = 5 K.','4200/(0,20 × 4200) = 5 K.'),o[0]))+
 example(t('Example 3 · Cooling, with a sign','3 pavyzdys · Vėsimas su ženklu'),[t('0.10 kg cools from 40 °C to 35 °C. ΔT = −5 K.','0,10 kg vandens vėsta nuo 40 °C iki 35 °C. ΔT = −5 K.'),t('Q to the water = 0.10 × 4200 × (−5) = −2100 J. It gives away a heat magnitude of 2100 J.','Q vandeniui = 0,10 × 4200 × (−5) = −2100 J. Atiduoto šilumos kiekio modulis 2100 J.')],1)+
 turn(quantity('p3',t('0.20 kg cools from 30 °C to 25 °C. Give signed Q **to the water**.','0,20 kg vandens vėsta nuo 30 °C iki 25 °C. Nurodyk Q **vandeniui** su ženklu.'),-4200,'energy-transfer','J|kJ','−4200 J',t('Q = 0.20 × 4200 × (25 − 30) = −4200 J.','Q = 0,20 × 4200 × (25 − 30) = −4200 J.'),o[2],wrong=[('4200',t('That is the magnitude given away; Q to the cooling water is negative.','Tai atiduoto kiekio modulis; Q vėstančiam vandeniui neigiamas.'))]))))
 b.append(block('check',t('Use the equation and challenge it','Taikyk lygtį ir patikrink jos ribas'),t('Core: questions 1–3. Questions 4–5 and the signed-cooling example are follow-up extensions. Complete the core and explain corrections before moving on; an automatic tick is only a practice record.','Pagrindas: 1–3 klausimai. 4–5 klausimai ir vėsimo su ženklu pavyzdys yra papildomos užduotys. Prieš tęsiant atlik pagrindą ir paaiškink klaidų pataisymus; automatinė žyma yra tik veiklos užrašas.')+
 quantity('c1',t('250 g of water warms from 18 °C to 26 °C. Find received Q.','250 g vandens pašildoma nuo 18 °C iki 26 °C. Rask gautą Q.'),8400,'energy-transfer','J|kJ',t('8400 J = 8.4 kJ','8400 J = 8,4 kJ'),t('m = 0.25 kg, ΔT = 8 K; Q = 0.25 × 4200 × 8 = 8400 J.','m = 0,25 kg, ΔT = 8 K; Q = 0,25 × 4200 × 8 = 8400 J.'),o[0],wrong=[('27300',t('Use the temperature change 8, not the final reading 26.','Naudok 8 pokytį, ne galutinį rodmenį 26.'))])+
 numeric('c2',t('In the 0.20 kg model, what is the temperature at 100 s? Read the graph or table.','Kokia 0,20 kg modelio temperatūra po 100 s? Skaityk grafiką arba lentelę.'),'25',t('At 100 s the table gives 25 °C. The rise is 5 K; the reading is 25 °C.','Po 100 s lentelėje 25 °C. Pokytis 5 K, o rodmuo 25 °C.'),o[1],wrong=[('5',t('5 is the change from the start, not the temperature reading.','5 yra pokytis nuo pradžios, ne temperatūros rodmuo.'))],unit='°C')+
 choice('c3',t('The same heat reaches equal masses of two materials, with no state change. Material A has twice the specific heat capacity of B. Which warms less?','Vienodas šilumos kiekis tenka dviem vienodos masės medžiagoms, būsena nekinta. A savitoji šiluma dvigubai didesnė už B. Kuri sušyla mažiau?'),[(t('A: its rise is half that of B.','A: jos pokytis perpus mažesnis nei B.'),True,t('ΔT = Q/(mc); a larger c means a smaller rise for fixed Q and m.','ΔT = Q/(mc); esant tam pačiam Q ir m, didesnis c reiškia mažesnį pokytį.')),(t('A: its rise is twice that of B.','A: jos pokytis dvigubai didesnis nei B.'),False,t('Specific heat capacity describes energy needed per degree, not how readily temperature rises.','Savitoji šiluma nusako energiją vienam laipsniui, ne temperatūros kilimo lengvumą.'))],t('A needs more energy per kelvin, so the same input raises its temperature less.','A vienam kelvinui reikia daugiau energijos, todėl tas pats kiekis pakelia temperatūrą mažiau.'),o[2])+
 choice('c4',t('Which observation challenges the unchanged-state model?','Kuris stebėjimas neatitinka nekintančios būsenos modelio?'),[(t('Ice melts while energy enters and the temperature stays constant.','Ledas lydosi, gauna energijos, o temperatūra nekinta.'),True,t('The energy goes into a phase change; Q = mcΔT alone cannot describe that segment.','Energija tenka faziniam virsmui; vien Q = mcΔT šio intervalo neaprašo.')),(t('A larger water mass warms more slowly at the same supplied power.','Didesnė vandens masė šyla lėčiau esant tai pačiai tiekiamai galiai.'),False,t('That is what the unchanged-state model predicts.','Tai numato nekintančios būsenos modelis.'))],t('A constant-temperature phase-change segment needs a different model, which comes later.','Pastovios temperatūros fazinio virsmo intervalui reikia kito modelio; jis bus vėliau.'),o[0])+
 task('c5',t('A real heater uses more than 8400 J while 0.20 kg of water warms by 10 K. Explain why this does not by itself disprove energy conservation. Include an annotated energy boundary.','Tikras šildytuvas sunaudoja daugiau nei 8400 J, kol 0,20 kg vandens sušyla 10 K. Paaiškink, kodėl tai savaime nepaneigia energijos tvermės. Nubraižyk energijos perdavimą per sistemos ribą.'),[t('Water-only gain is 8400 J.','Vien vandens gauta energija 8400 J.'),t('Identify container and/or surroundings as additional recipients.','Nurodytas indas ir (arba) aplinka kaip papildomi energijos gavėjai.'),t('Explain that the simple model ignores those transfers.','Paaiškinta, kad paprastas modelis šių perdavimų nepaiso.')],t('The 8400 J calculation estimates the gain of the water alone. The container can also warm and energy can reach the surroundings. Compare all inputs and gains for the chosen system rather than equating electrical input with the water-only gain.','8400 J skaičiavimas nusako tik vandens energijos padidėjimą. Gali šilti ir indas, o energija patekti į aplinką. Pasirink tai, ką laikai sistema, ir palygink visus perdavimus bei pokyčius, o ne automatiškai prilygink elektros energiją vien vandens energijos pokyčiui.'),o[0])))
 b.append(block('summary',t('Five checks before substituting','Penkios patikros prieš įstatant'),t('Identify the system; check that its state stays the same; convert mass to kg; calculate final − initial; give the answer with a unit and sign convention. In the graph, distinguish a reading, a change and a slope. $c$ describes the material; changing mass does not change its specific heat capacity.','Apibrėžk sistemą; patikrink, kad būsena nekinta; masę perskaičiuok į kg; apskaičiuok galutinė minus pradinė; atsakyk su vienetu ir ženklų sutartimi. Grafike atskirk rodmenį, pokytį ir nuolydį. $c$ nusako medžiagą; keičiant masę jos savitoji šiluma nesikeičia.')+'\n\n<Next>'+t('Can a supervised mixing experiment test a heat-balance prediction?','Ar prižiūrimas maišymo tyrimas gali patikrinti šilumos balanso prognozę?')+'</Next>'))
 b.append(block('teacher',t('Teaching route and misconceptions','Pamokos eiga ir būdingos klaidos'),t('**45-minute core:** recall 4 min; prediction 4; equation frames 9; graph model 8; examples 10; checks 8; exit boundary sketch 2. The reverse calculation and written challenge can become follow-up practice. These timings need classroom validation.\n\nAsk pupils to predict before changing the model’s mass, and justify with a ratio before calculating. Compare ΔT and final T explicitly. Typical errors: grams substituted as kg; final temperature used for ΔT; larger c interpreted as larger temperature rise; cooling sign omitted; plateau declared “no energy transfer”.\n\n**Terms EN · LT:** specific heat capacity · savitoji šiluma; temperature change · temperatūros pokytis; slope · nuolydis; heat received/given away · gautas/atiduotas šilumos kiekis. The checker accepts J and kJ but requires the numerical value to match the chosen unit.\n\nNo physical heater is needed. The data and visualisation are ideal-model values, not measurements. This addresses only the constant-state and graph foundations within the much broader changes-of-state programme node. Human review is pending.','**45 min pagrindas:** prisiminimas 4 min; prognozė 4; lygties aiškinimas 9; grafiko modelis 8; pavyzdžiai 10; pasitikrinimas 8; baigiamasis sistemos ribos brėžinys 2. Atvirkštinį skaičiavimą ir rašytinę užduotį galima skirti vėliau. Laiką reikia patikrinti klasėje.\n\nPrieš keičiant modelio masę prašykite prognozės ir santykio paaiškinimo. Aiškiai palyginkite ΔT ir galutinę T. Būdingos klaidos: gramai vietoje kg; galutinė temperatūra vietoje ΔT; didesnis c suprantamas kaip didesnis temperatūros pokytis; praleistas vėsimo ženklas; horizontali atkarpa laikoma „energija neperduodama“.\n\n**Terminai EN · LT:** specific heat capacity · savitoji šiluma; temperature change · temperatūros pokytis; slope · nuolydis; heat received/given away · gautas/atiduotas šilumos kiekis. Tikrintuvas priima J ir kJ, bet skaičius turi atitikti pasirinktą vienetą.\n\nTikro šildytuvo nereikia. Duomenys ir vaizdas yra idealaus modelio reikšmės, ne matavimai. Aptariami tik nekintančios būsenos ir grafiko pagrindai, sudarantys dalį platesnės būsenų kitimo programos temos. Žmogaus peržiūra dar neatlikta.')))
 return ''.join(b)

def lesson3():
 o=[f'g9.thermal.{i}' for i in range(7,10)];b=[]
 b.append(block('remember',t('Before collecting evidence','Prieš renkant įrodymus'),quantity('r1',t('0.10 kg of water warms by 10 K. With c = 4200 J/(kg·K), find Q.','0,10 kg vandens sušyla 10 K. Kai c = 4200 J/(kg·K), rask Q.'),4200,'energy-transfer','J|kJ','4200 J',t('0.10 × 4200 × 10 = 4200 J.','0,10 × 4200 × 10 = 4200 J.'),o[0])+
 choice('r2',t('What does a negative signed Q to the water mean?','Ką reiškia neigiamas Q vandeniui su ženklu?'),[(t('The water gives energy away as heat.','Vanduo atiduoda energiją šiluma.'),True,t('We chose positive for heat received.','Teigiamą ženklą pasirinkome gaunamai šilumai.')),(t('Its temperature must be below 0 °C.','Jo temperatūra būtinai žemesnė už 0 °C.'),False,t('The sign describes a transfer, not an absolute temperature reading.','Ženklas nusako perdavimą, ne absoliučią temperatūrą.'))],t('A cooling sample can have a positive temperature and a negative heat transfer to it.','Vėstančio vandens temperatūra gali būti teigiama, nors Q vandeniui neigiamas.'),o[0])))
 b[-1]=b[-1].replace('\n\n</Block>', '\n\n'+choice('r3',t('A thermometer display changes in 0.1 °C steps. What can you record directly?','Termometro rodmuo kinta 0,1 °C žingsniais. Ką gali tiesiogiai užrašyti?'),[(t('Its displayed resolution is 0.1 °C.','Mažiausias rodomas žingsnis yra 0,1 °C.'),True,t('Resolution describes the displayed step; a full uncertainty assessment needs more information.','Padalos vertė nusako rodomą žingsnį; visai paklaidai įvertinti reikia daugiau informacijos.')),(t('All measurements are exactly correct to 0.001 °C.','Visi matavimai tikslūs iki 0,001 °C.'),False,t('Extra digits and an accuracy guarantee do not follow from the display step.','Papildomi skaitmenys ir tikslumo garantija neišplaukia iš rodomo žingsnio.'))],t('Record resolution separately from assumptions about measurement uncertainty.','Padalos vertę užrašyk atskirai nuo prielaidų apie matavimo paklaidą.'),o[1])+'\n\n</Block>')
 b.append(block('hook',t('Will the mixture be exactly halfway?','Ar mišinys bus tiksliai per vidurį?'),t('Your class will mix equal measured masses of cool water near 20 °C and warm water at or below 40 °C. Before touching the equipment, predict the final temperature and list what could make a real result differ. “It should be 30 °C” is a model prediction, not permission to write 30 into the results table.','Klasėje sumaišysite vienodas išmatuotas vėsaus, apie 20 °C, ir šilto, ne aukštesnės kaip 40 °C, vandens mases. Prieš imdamas įrangą numatyk galutinę temperatūrą ir išvardyk, kas tikrą rezultatą galėtų pakeisti. „Turėtų būti 30 °C“ yra modelio prognozė, ne leidimas į rezultatų lentelę įrašyti 30.')))
 b.append(block('explain',t('Plan a safe and interpretable test','Suplanuok saugų ir prasmingą tyrimą'),frames([
 (t('System and question','Sistema ir klausimas'),t('Choose the two portions of water together as the calculation system. Ask: “How close is the measured mixture temperature to an ideal heat-balance prediction?” The simple model omits energy changes of the cup, thermometer and surroundings. Record what is omitted before the experiment; do not decide the assumptions after seeing a result.','Skaičiavimo sistema – abi vandens dalys kartu. Klausimas: „Kiek išmatuota mišinio temperatūra artima idealaus šilumos balanso prognozei?“ Paprastas modelis neįtraukia puodelio, termometro ir aplinkos energijos pokyčių. Prieš tyrimą užrašyk, ko nepaisoma; prielaidų nepasirink tik pamatęs rezultatą.')),
 (t('Equipment and safety','Įranga ir sauga'),t('**Teacher-supervised classroom activity only.** Use two stable cups, an insulated mixing cup, a balance, a mercury-free thermometer suitable for water (preferably a digital probe), a timer, water and a spill cloth. Aim for about 100 g in each portion. The teacher prepares warm water at **35–40 °C, never above 40 °C**, and checks its temperature before distribution. Pupils do not operate kettles or heat water.\n\nKeep cups away from desk edges and electrical equipment. Do not drink the water. Stir gently without splashing; report spills and dry the surface. If glass breaks, stop, keep away and let the teacher follow the school’s clean-up procedure. If safe equipment or supervision is unavailable, analyse the clearly labelled example data in lesson 4 instead; do not improvise a home heating experiment.','**Tik mokytojo prižiūrima veikla klasėje.** Reikia dviejų stabilių indų, izoliuoto maišymo indo, svarstyklių, vandeniui tinkamo termometro be gyvsidabrio (geriausia skaitmeninio zondo), laikmačio, vandens ir šluostės. Siekite maždaug 100 g kiekvienoje dalyje. Mokytojas paruošia **35–40 °C, ne aukštesnės kaip 40 °C**, vandenį ir prieš dalydamas patikrina temperatūrą. Mokiniai nenaudoja virdulių ir vandens nekaitina.\n\nIndus laikykite atokiau nuo stalo krašto ir elektros įrangos. Vandens negerkite. Maišykite švelniai, netaškykite; apie išsiliejimą praneškite ir nusausinkite paviršių. Sudužus stiklui sustokite, atsitraukite ir leiskite mokytojui tvarkyti pagal mokyklos procedūrą. Jei nėra saugios įrangos ar priežiūros, analizuokite aiškiai pažymėtus 4 pamokos pavyzdžio duomenis; neimprovizuokite šildymo namuose.')),
 (t('Which quantities to record','Kokius dydžius užrašyti'),t('Measure each water mass; do not replace it with the intended “100 g”. Tare the container or subtract its empty mass. Record thermometer and balance resolution (smallest displayed step or scale division), not an invented uncertainty. Put the cool water into the insulated mixing cup; record that cup’s initial condition. Use one thermometer: measure cool water first, then warm water, allowing it to settle each time; record the order and times. Pour warm water into the cool water in that same insulated cup immediately after the warm reading. Measure both initial temperatures as close to mixing as practical.\n\nUse the same protocol in each trial: container, stirring, reading criterion and timing. A changed mass is a changed input, so it must appear in the record and prediction.','Išmatuok kiekvienos vandens dalies masę; jos nepakeisk numatytu „100 g“. Nunulink svarstykles su indu arba atimk tuščio indo masę. Užrašyk termometro ir svarstyklių mažiausią rodomą žingsnį arba padalos vertę, ne išgalvotą paklaidą. Vėsų vandenį laikyk izoliuotame maišymo inde; užrašyk jo pradinę būklę. Naudok vieną termometrą: pirmiausia išmatuok vėsų, paskui šiltą vandenį, kiekvieną kartą palauk rodmens nusistovėjimo; užrašyk eilę ir laiką. Iškart po šilto rodmens šiltą vandenį pilk į vėsų tame pačiame izoliuotame inde. Abi pradines temperatūras išmatuok kiek įmanoma arčiau maišymo.\n\nAbiem bandymams taikyk tą patį protokolą: indas, maišymas, nuskaitymo kriterijus ir laikas. Pakitusi masė yra kitoks pradinis dydis, todėl ji turi būti užraše ir prognozėje.')),
 (t('Define the reading time','Apibrėžk nuskaitymo laiką'),t('For this protocol, use this operational rule: while stirring gently, the display stays within one displayed step for 5 s. Record that reading as the **first stable reading** and $t_{\mathrm{reading}}=0$. This criterion does not prove exact thermal equilibrium. The separate pouring clock starts at the start of pouring. Note how many seconds elapsed from pouring to that reading. Then record the temperature at +30 s and +60 s. Keep the thermometer immersed appropriately, without touching the cup wall or bottom, and follow its manufacturer’s instructions.\n\nFor a detailed residual comparison, use a thermometer with 0.1 °C resolution or finer and check its documented accuracy; resolution alone is not accuracy. A 1 °C thermometer supports only a rough temperature-range comparison. A later drift can indicate ongoing exchange with the surroundings; it cannot on its own measure the heat exchanged during the whole mixing process.','Šiame protokole taikyk šį darbinį kriterijų: švelniai maišant rodmuo 5 s lieka vieno rodomo žingsnio intervale. Jį užrašyk kaip **pirmą nusistovėjusį rodmenį** ir $t_{\mathrm{rodmens}}=0$. Šis kriterijus neįrodo tikslios šiluminės pusiausvyros. Atskiras pylimo laikmatis pradedamas pradėjus pilti. Užrašyk, kiek sekundžių praėjo nuo pylimo iki šio rodmens. Tada išmatuok temperatūrą po +30 s ir +60 s. Termometrą tinkamai panardink, neliesk indo sienelės ar dugno ir laikykis jo gamintojo instrukcijų.\n\nIšsamiai liekanai palyginti naudok 0,1 °C ar smulkesnio žingsnio termometrą ir patikrink jo nurodytą tikslumą; padalos vertė nėra tikslumas. 1 °C termometras leidžia tik apytiksliai palyginti temperatūrų intervalą. Vėlesnis kitimas gali rodyti tęstinius šilumos mainus su aplinka; vien juo viso maišymo proceso šilumos mainų neapskaičiuosi.'))])))
 table=t('''| Trial | Cool mass (g) | Warm mass (g) | Initial cool T (°C) | Initial warm T (°C) | First stable T (°C) | Delay (s) | T at +30 s (°C) | T at +60 s (°C) |
|---|---|---|---|---|---|---|---|---|
| 1 | ____ | ____ | ____ | ____ | ____ | ____ | ____ | ____ |
| 2 | ____ | ____ | ____ | ____ | ____ | ____ | ____ | ____ |

Balance resolution: ____ g. Thermometer resolution: ____ °C. Container initial condition: ____. Pour direction: warm into cool. Initial-reading order/times: ____. Stability criterion: one step over 5 s.''','''| Bandymas | Vėsaus masė (g) | Šilto masė (g) | Pradinė vėsaus T (°C) | Pradinė šilto T (°C) | Pirma nusistovėjusi T (°C) | Delsa (s) | T po +30 s (°C) | T po +60 s (°C) |
|---|---|---|---|---|---|---|---|---|
| 1 | ____ | ____ | ____ | ____ | ____ | ____ | ____ | ____ |
| 2 | ____ | ____ | ____ | ____ | ____ | ____ | ____ | ____ |

Svarstyklių padalos vertė: ____ g. Termometro padalos vertė: ____ °C. Pradinė indo būklė: ____. Pylimo kryptis: šiltas į vėsų. Pradinių rodmenų eilė ir laikas: ____. Nusistovėjimo kriterijus: vienas žingsnis per 5 s.''')
 b.append(block('explore',t('Collect your own evidence','Surink savo įrodymus'),t('1. Record the equipment and instrument resolutions; check the teacher’s safety instructions.\n2. Measure actual masses and initial temperatures, and write your prediction.\n3. Under teacher supervision, pour warm water into the cool water already in the insulated cup and stir gently. Record the first stable reading, its delay and the later readings.\n4. Repeat once using the same protocol. Record new actual inputs.\n5. Keep every raw reading. If no reading is available, write “not measured”, rather than filling it from the model.\n\n**Blank record for real measurements:**','1. Užrašyk įrangą ir prietaisų padalos vertes; patikrink mokytojo saugos nurodymus.\n2. Išmatuok tikras mases ir pradines temperatūras, parašyk prognozę.\n3. Mokytojui prižiūrint šiltą vandenį pilk į vėsų, esantį izoliuotame inde, ir švelniai išmaišyk. Užrašyk pirmą nusistovėjusį rodmenį, jo delsą ir vėlesnius rodmenis.\n4. Pakartok tuo pačiu protokolu. Išmatuok ir užrašyk naujus tikrus pradinius dydžius.\n5. Išsaugok visus pirminius rodmenis. Jei rodmens nėra, rašyk „neišmatuota“, ne modelio skaičių.\n\n**Tuščia tikrų matavimų lentelė:**')+'\n\n'+table))
 b.append(block('examples',t('Make the record usable','Parenk suprantamą užrašą'),
 example(t('Example 1 · A mass entry','1 pavyzdys · Masės įrašas'),[t('Suppose, as an illustrative entry, an empty cup is 32 g and cup + water is 131 g.','Tarkime, iliustraciniame įraše tuščias indas sveria 32 g, indas su vandeniu – 131 g.'),t('Water mass = 131 − 32 = 99 g = 0.099 kg. Record 99 g, not the target 100 g. These are example values, not your trial.','Vandens masė = 131 − 32 = 99 g = 0,099 kg. Užrašyk 99 g, ne numatytus 100 g. Tai pavyzdžio skaičiai, ne tavo bandymas.')])+
 turn(numeric('p1',t('Illustrative entry: empty cup 28 g; cup + water 130 g. Find water mass.','Iliustracinis įrašas: tuščias indas 28 g; indas su vandeniu 130 g. Rask vandens masę.'),'102',t('130 − 28 = 102 g.','130 − 28 = 102 g.'),o[1],unit='g'))+
 example(t('Example 2 · A time label','2 pavyzdys · Laiko žyma'),[t('The first stable reading occurs 12 s after pouring. Label that reading t = 0 and record delay = 12 s.','Pirmas nusistovėjęs rodmuo gaunamas po 12 s nuo pylimo. Jam žymėk t = 0 ir užrašyk delsą = 12 s.'),t('A +30 s reading is taken 42 s after pouring. Do not label the first reading as an instantaneous pouring temperature.','+30 s rodmuo gaunamas po 42 s nuo pylimo. Pirmo rodmens nevadink pylimo akimirkos temperatūra.')],1)+
 turn(numeric('p2',t('First stable reading occurs 15 s after pouring. The +60 s reading occurs how many seconds after pouring?','Pirmas nusistovėjęs rodmuo gautas po 15 s nuo pylimo. Po kiek sekundžių nuo pylimo gaunamas +60 s rodmuo?'),'75',t('15 + 60 = 75 s.','15 + 60 = 75 s.'),o[2],unit='s'))+
 example(t('Example 3 · A cautious observation','3 pavyzdys · Atsargi stebėjimo išvada'),[t('A later reading is lower than the first stable reading.','Vėlesnis rodmuo mažesnis už pirmą nusistovėjusį.'),t('Write: “The reading decreased over this interval; continued heat exchange or measurement effects may contribute.” Do not write an exact environmental heat loss without a suitable model and data.','Rašyk: „Šiame intervale rodmuo sumažėjo; galėjo prisidėti tęstiniai šilumos mainai ar matavimo ypatumai.“ Be tinkamo modelio ir duomenų nerašyk tikslaus aplinkai atiduoto šilumos kiekio.')],1)))
 b.append(block('check',t('A readiness check, not invented results','Pasirengimo patikra, ne išgalvoti rezultatai'),
 choice('c1',t('The measured masses are 97 g and 103 g. Which inputs should the analysis use?','Išmatuotos masės 97 g ir 103 g. Kokius dydžius naudoti analizei?'),[(t('0.097 kg and 0.103 kg.','0,097 kg ir 0,103 kg.'),True,t('Use each actual mass and convert it to kg.','Naudok tikras mases, perskaičiuotas į kg.')),(t('0.100 kg and 0.100 kg because that was the plan.','0,100 kg ir 0,100 kg, nes taip planuota.'),False,t('Changing data to match the plan removes evidence about the actual experiment.','Pritaikydamas duomenis prie plano prarandi tikro tyrimo įrodymus.'))],t('Actual inputs belong in both the record and the prediction.','Tikri pradiniai dydžiai turi būti ir lentelėje, ir prognozėje.'),o[1])+
 choice('c2',t('What should happen if the prepared water is 46 °C?','Ką daryti, jei paruošto vandens temperatūra 46 °C?'),[(t('Stop and ask the teacher to bring it within the protocol’s limit.','Sustoti ir paprašyti mokytojo užtikrinti protokolo temperatūros ribą.'),True,t('The maximum for this trial protocol is 40 °C.','Šio bandomojo protokolo riba 40 °C.')),(t('Pour it quickly before it cools.','Greitai supilti, kol neatvėso.'),False,t('Speed does not replace the specified safety condition.','Skubėjimas nepakeičia saugos sąlygos.'))],t('Do not proceed above the 40 °C limit. Teacher preparation and supervision are required.','Viršijus 40 °C ribą veiklos netęsk. Reikia mokytojo paruošimo ir priežiūros.'),o[0])+
 choice('c3',t('Which is the t = 0 reading in this protocol?','Kuris rodmuo šiame protokole yra t = 0?'),[(t('The first stable mixed-water reading, with its delay recorded.','Pirmas nusistovėjęs mišinio rodmuo, užrašius jo delsą.'),True,t('The timing definition makes trials interpretable.','Apibrėžtas laikas leidžia prasmingai lyginti bandymus.')),(t('An assumed 30 °C at the instant of pouring.','Numanoma 30 °C pylimo akimirką.'),False,t('That is neither an actual reading nor the protocol’s time definition.','Tai nei tikras rodmuo, nei protokolo laiko apibrėžimas.'))],t('Record what was observed and when. The first stable reading is not instantaneous.','Užrašyk, kas stebėta ir kada. Pirmas nusistovėjęs rodmuo nėra momentinis.'),o[2])+
 choice('c4',t('Why record the container and use the same one in both trials?','Kodėl užrašome indą ir abiem bandymams naudojame tą patį?'),[(t('It can exchange energy with the water; changing it changes the conditions.','Jis gali keistis energija su vandeniu; pakeistas indas keičia sąlygas.'),True,t('The water-only model ignores the container, but the experiment does not remove it.','Vien vandens modelis indo nepaiso, tačiau tyrime jis neišnyksta.')),(t('Insulation guarantees the container has no effect.','Izoliacija garantuoja, kad indas nedaro įtakos.'),False,t('Insulation reduces exchange with surroundings; the container can still warm.','Izoliacija mažina mainus su aplinka; pats indas vis tiek gali šilti.'))],t('Keep conditions documented and consistent; state the container omission in the model.','Dokumentuok ir išlaikyk sąlygas; nurodyk, kad modelis neįtraukia indo.'),o[2])+
 task('c5',t('Submit a short investigation record: question, system, prediction, safety check, two raw-data rows and one limitation. If no experiment was performed, submit the plan only and explicitly state “not performed”; use no invented measurements.','Pateik trumpą tyrimo užrašą: klausimas, sistema, prognozė, saugos patikra, dvi pirminių duomenų eilutės ir viena modelio riba. Jei tyrimas neatliktas, pateik tik planą ir aiškiai parašyk „neatlikta“; neišgalvok matavimų.'),[t('State a testable question and the water system.','Nurodytas tikrinamas klausimas ir vandens sistema.'),t('Include supervision, 40 °C limit and actual equipment.','Nurodyta priežiūra, 40 °C riba ir tikra įranga.'),t('Preserve actual readings with units and timing, or clearly label the plan-only status.','Išsaugoti tikri rodmenys su vienetais ir laiku arba aiškiai pažymėta, kad pateiktas tik planas.'),t('Explain at least one omitted influence and a way to improve consistency.','Paaiškintas bent vienas neįtrauktas veiksnys ir nuoseklumo gerinimas.')],t('There is no universal results row: use your measurements. A plan-only submission can explain equal-mass midpoint prediction, water-only system, supervised warm water ≤40 °C, mass/temperature measurements, consistent stable-reading criterion, and the possible container influence. Do not call this experimental evidence if it was not performed.','Vienos visiems tinkamos rezultatų eilutės nėra: naudok savo matavimus. Tik planą pateikiantis mokinys gali nurodyti vienodų masių vidurio prognozę, sistemą iš abiejų vandens dalių, mokytojo priežiūrą ir ≤40 °C vandenį, masių ir temperatūrų matavimą, nuoseklų nusistovėjusio rodmens kriterijų ir indo įtaką. Jei tyrimas neatliktas, to nevadink eksperimentiniais įrodymais.'),o[0])))
 b.append(block('summary',t('A good record survives a surprising result','Geras užrašas išlieka vertingas net nustebus'),t('Record actual inputs, instrument resolution, first stable reading and its delay. Keep the same protocol in two trials. A prediction and a measurement serve different purposes. A lower-than-predicted reading invites analysis of assumptions; it is not a reason to rewrite the data.','Užrašyk tikrus pradinius dydžius, prietaisų padalos vertes, pirmą nusistovėjusį rodmenį ir jo delsą. Abiem bandymams taikyk tą patį protokolą. Prognozė ir matavimas skirti skirtingiems tikslams. Mažesnis už prognozę rodmuo kviečia nagrinėti prielaidas, o ne taisyti duomenis.')+'\n\n<Next>'+t('Use your record to compare heat gained, heat lost and the ideal prediction.','Panaudok užrašą gautai ir atiduotai šilumai bei idealiai prognozei palyginti.')+'</Next>'))
 b.append(block('teacher',t('Prepare before the class','Pasiruošk prieš pamoką'),t('**Before use:** perform the protocol yourself with the actual cups, balance and thermometer; confirm stable-reading response time and handling. No laboratory trial or teacher sign-off is claimed. Water limit ≤40 °C is this protocol’s chosen condition; follow your school’s procedures too.\n\n**45-minute route:** readiness and prediction 7 min; equipment/safety and time definition 8; two supervised trials 20; record check 5; limitations and exit response 5. Allocate analysis to lesson 4. If two safe trials cannot fit, retain a complete single trial and schedule the second later rather than rushing.\n\nThe readiness questions assess procedural understanding, not competence with real equipment. Review the submitted record directly; the website cannot automatically judge physical execution or written evidence.\n\n**Terms EN · LT:** measured mass · išmatuota masė; instrument resolution · prietaiso padalos vertė / mažiausias rodomas žingsnis; first stable reading · pirmas nusistovėjęs rodmuo; delay · delsa; system boundary · sistemos riba.\n\nThis water-mixing activity is a partial energy-conservation investigation. It does not fulfil the separate programme activity of determining the specific heat of an unknown material.','**Prieš naudojimą:** patys išbandykite protokolą su tikrais indais, svarstyklėmis ir termometru; patikrinkite nusistovėjimo laiką ir naudojimą. Laboratorinio bandymo ir mokytojo patvirtinimo dar nėra. ≤40 °C riba yra pasirinkta šio protokolo sąlyga; laikykitės ir mokyklos tvarkos.\n\n**45 min eiga:** pasirengimas ir prognozė 7 min; įranga, sauga ir laiko apibrėžimas 8; du prižiūrimi bandymai 20; užrašų patikra 5; ribos ir baigiamasis atsakymas 5. Analizė skirta 4 pamokai. Jei du saugūs bandymai netelpa, išsaugokite vieną pilną bandymą, o antrą atlikite vėliau; neskubinkite veiklos.\n\nPasirengimo klausimai tikrina procedūros supratimą, ne gebėjimą naudoti tikrą įrangą. Tyrimo užrašą peržiūrėkite tiesiogiai; svetainė negali automatiškai įvertinti fizinio atlikimo ar rašytinių įrodymų.\n\n**Terminai EN · LT:** measured mass · išmatuota masė; instrument resolution · prietaiso padalos vertė / mažiausias rodomas žingsnis; first stable reading · pirmas nusistovėjęs rodmuo; delay · delsa; system boundary · sistemos riba.\n\nŠi vandens maišymo veikla iš dalies tiria energijos tvermę. Ji neatstoja atskiros programos veiklos, kurioje nustatoma nežinomos medžiagos savitoji šiluma.')))
 return ''.join(b)

def lesson4():
 o=[f'g9.thermal.{i}' for i in range(10,13)];b=[]
 b.append(block('remember',t('Two temperature changes','Du temperatūros pokyčiai'),
 quantity('r1',t('Cool water changes from 20 °C to 29 °C. Give signed ΔT.','Vėsaus vandens temperatūra pakinta nuo 20 °C iki 29 °C. Nurodyk ΔT su ženklu.'),9,'temperature-difference','K|°C','9 K',t('29 − 20 = +9 K.','29 − 20 = +9 K.'),o[1])+
 quantity('r2',t('Warm water changes from 40 °C to 29 °C. Give signed ΔT.','Šilto vandens temperatūra pakinta nuo 40 °C iki 29 °C. Nurodyk ΔT su ženklu.'),-11,'temperature-difference','K|°C','−11 K',t('29 − 40 = −11 K. The magnitude given away will be positive.','29 − 40 = −11 K. Atiduoto šilumos kiekio modulis bus teigiamas.'),o[1])+
 t('Use your actual masses and initial readings from lesson 3 if a supervised trial was performed. The example data below are a separate, explicitly synthetic practice set.','Jei atlikote prižiūrimą bandymą, naudok savo tikras mases ir pradinius rodmenis iš 3 pamokos. Žemiau esantys pavyzdžio duomenys yra atskiras, aiškiai sintetinis pratybų rinkinys.')))
 b.append(block('hook',t('A prediction is not a result','Prognozė nėra rezultatas'),t('Equal masses start at 20 °C and 40 °C. The ideal model predicts 30 °C; practice data give 29.2 °C. Does the difference mean energy has disappeared? Name the system and write one assumption you would check before drawing a conclusion.','Vienodos masės iš pradžių yra 20 °C ir 40 °C. Idealus modelis numato 30 °C; pratybų duomenyse pateikta 29,2 °C. Ar skirtumas reiškia, kad energija išnyko? Prieš darydamas išvadą nurodyk sistemą ir parašyk vieną tikrintiną prielaidą.')))
 b.append(block('explain',t('Balance transfers and inspect assumptions','Subalansuok perdavimus ir patikrink prielaidas'),frames([
 (t('The ideal water-only balance','Idealus vien vandens balansas'),t('Both portions are the same material; no state changes occur. Lesson 3 pours warm into cool water in the insulated cup. A cup initially near the cool temperature can gain energy and lower the final reading compared with the water-only prediction. Pouring into a warm cup could reverse that contribution; the residual sign is not fixed by conservation alone. Ignore the container, thermometer, heat exchange with surroundings and stirring work. Let warm water give away a **positive magnitude** $Q_w$, while cool water receives positive $Q_c$.\n\n$$m_w c(T_w-T_f)=m_c c(T_f-T_c).$$\n\nThe temperature differences here are positive magnitudes. This is equivalent to the sum of signed transfers to the water being zero. Do not mix signed Q with positive magnitudes halfway through a solution.','Abi dalys yra ta pati medžiaga, būsena nekinta. 3 pamokoje šiltas vanduo pilamas į vėsų izoliuotame inde. Indas, kurio pradinė temperatūra artima vėsiam vandeniui, gali gauti energijos ir sumažinti galutinį rodmenį, palyginti su vien vandens prognoze. Pilant į šiltą indą jo indėlis galėtų būti priešingas; vien tvermė nenustato liekanos ženklo. Nepaisome indo, termometro, mainų su aplinka ir maišymo darbo. Šiltas vanduo atiduoda **teigiamą modulį** $Q_w$, vėsus gauna teigiamą $Q_c$.\n\n$$m_w c(T_w-T_f)=m_c c(T_f-T_c).$$\n\nČia temperatūrų skirtumai yra teigiami moduliai. Tai lygiavertė sąlyga, kad šilumos perdavimų vandeniui su ženklais suma lygi nuliui. Sprendimo viduryje nekeisk ženklų sutarties.')),
 (t('The midpoint requires equal masses','Viduriui reikia vienodų masių'),t('For the same water, $c$ cancels. Rearranging gives\n\n$$T_f=\\frac{m_wT_w+m_cT_c}{m_w+m_c}.$$\n\nEqual masses give the arithmetic midpoint. Unequal masses give a **mass-weighted** temperature closer to the larger portion’s initial temperature. The result must be between the two initial temperatures under these assumptions. In kelvin, equal masses give (293.15 + 313.15)/2 = 303.15 K, which is the same 30 °C. A weighted mean shifts by the scale offset too.','Tam pačiam vandeniui $c$ susiprastina. Pertvarkę gauname\n\n$$T_f=\\frac{m_wT_w+m_cT_c}{m_w+m_c}.$$\n\nVienodos masės duoda aritmetinį vidurį. Nevienodos masės duoda **mase svertą** temperatūrą, artimesnę didesnės dalies pradinei temperatūrai. Esant šioms prielaidoms, rezultatas turi būti tarp pradinių temperatūrų. Kelvinais vienodoms masėms gauname (293,15 + 313,15)/2 = 303,15 K, tai tie patys 30 °C. Svertinis vidurkis taip pat pasislenka per skalių poslinkį.')),
 (t('What a discrepancy tells us','Ką pasako skirtumas'),t('Using a final reading, calculate $Q_c=m_cc(T_f-T_c)$ and $Q_w=m_wc(T_w-T_f)$. Their difference $R=Q_w-Q_c$ is a **water-only balance residual**. A positive R says the warm-water decrease exceeds the cool-water increase in this calculation.\n\nIt is not automatically the exact heat lost to the room. Energy may warm the cup and thermometer; readings, masses and timing may also affect R. Conservation concerns a sufficiently complete system and all transfers, not equality of two incomplete estimates.','Pagal galutinį rodmenį apskaičiuok $Q_c=m_cc(T_f-T_c)$ ir $Q_w=m_wc(T_w-T_f)$. Skirtumas $R=Q_w-Q_c$ yra **vien vandens balanso liekana**. Teigiamas R rodo, kad šiame skaičiavime šilto vandens energijos sumažėjimas didesnis už vėsaus padidėjimą.\n\nTai nėra automatiškai tikslus kambariui perduotas šilumos kiekis. Energija gali šildyti indą bei termometrą; R veikia rodmenys, masės ir laikas. Tvermė taikoma pakankamai pilnai sistemai ir visiems perdavimams, ne dviejų nepilnų įverčių lygybei.'))])))
 b.append(block('explore',t('Change the mass, test your prediction','Keisk masę, patikrink prognozę'),t('This is an **ideal model, not measurements**. Cool water stays at 0.10 kg and 20 °C; warm water starts at 40 °C. Predict where final T moves if you double the warm mass. Then select 0.20 kg. Explain why the arithmetic midpoint no longer applies. Use the table if the figure cannot be read. In a real experiment, use measured initial temperatures rather than replacing them with 20 and 40.','Tai **idealus modelis, ne matavimai**. Vėsaus vandens masė 0,10 kg, pradinė temperatūra 20 °C; šiltas vanduo pradžioje 40 °C. Numatyk, kur pasislinks galutinė T padvigubinus šilto vandens masę. Tada pasirink 0,20 kg. Paaiškink, kodėl aritmetinis vidurys nebetinka. Jei vaizdo negali perskaityti, naudok lentelę. Tikram bandymui naudok išmatuotas pradines temperatūras, nepakeisk jų 20 ir 40.'),'thermal-model','mixing'))
 b.append(block('examples',t('From prediction to residual','Nuo prognozės iki liekanos'),
 example(t('Example 1 · Equal masses','1 pavyzdys · Vienodos masės'),[t('For 0.10 kg at 20 °C and 0.10 kg at 40 °C, state the ideal assumptions.','0,10 kg 20 °C ir 0,10 kg 40 °C vandeniui nurodyk idealaus modelio prielaidas.'),t('$T_f=(0.10\\times20+0.10\\times40)/0.20=30\\ ^\\circ\\mathrm{C}$. This is 303.15 K, between the two initial temperatures.','$T_f=(0{,}10\\times20+0{,}10\\times40)/0{,}20=30\\ ^\\circ\\mathrm{C}$. Tai 303,15 K, tarp pradinių temperatūrų.')])+
 turn(quantity('p1',t('Equal masses start at 18 °C and 36 °C. Find ideal T.','Vienodų masių pradinės temperatūros 18 °C ir 36 °C. Rask idealią T.'),300.15,'absolute-temperature','°C|K',t('27 °C = 300.15 K','27 °C = 300,15 K'),t('(18 + 36)/2 = 27 °C.','(18 + 36)/2 = 27 °C.'),o[0]))+
 example(t('Example 2 · Twice as much warm water','2 pavyzdys · Dvigubai daugiau šilto vandens'),[t('Cool: 0.10 kg at 20 °C. Warm: 0.20 kg at 40 °C. Use the weighted formula.','Vėsus: 0,10 kg 20 °C. Šiltas: 0,20 kg 40 °C. Taikyk svertinę formulę.'),t('$T_f=(0.10\\times20+0.20\\times40)/0.30\\approx33.3\\ ^\\circ\\mathrm{C}$. It is closer to the larger warm portion.','$T_f=(0{,}10\\times20+0{,}20\\times40)/0{,}30\\approx33{,}3\\ ^\\circ\\mathrm{C}$. Temperatūra artimesnė didesnei šiltai daliai.')],1)+
 turn(quantity('p2',t('Reverse the masses: 0.20 kg cool at 20 °C; 0.10 kg warm at 40 °C. Give ideal T to one decimal place.','Sukeisk mases: 0,20 kg vėsaus 20 °C; 0,10 kg šilto 40 °C. Nurodyk idealią T vieno dešimtainio ženklo tikslumu.'),299.8166666667,'absolute-temperature','°C|K',t('26.7 °C','26,7 °C'),t('(0.20 × 20 + 0.10 × 40)/0.30 ≈ 26.7 °C.','(0,20 × 20 + 0,10 × 40)/0,30 ≈ 26,7 °C.'),o[0],wrong=[('30',t('The masses are unequal; use weights, not the midpoint.','Masės nevienodos; taikyk svorius, ne vidurį.'))],tolerance=.051))+
 t('**Synthetic practice data. Not measured by a pupil or the author.** Both practice trials use 0.100 kg initially at 20.0 °C and 0.100 kg at 40.0 °C. These values practise analysis; they do not validate the laboratory protocol.','**Sintetiniai pratybų duomenys. Ne mokinio ar autoriaus matavimai.** Abiem pratybų bandymams imta 0,100 kg 20,0 °C ir 0,100 kg 40,0 °C vandens. Skaičiai skirti analizei mokytis; jie nepatvirtina laboratorinio protokolo.')+'\n\n'+
 t('| Practice trial | First stable T (°C) | Delay (s) | T at +30 s (°C) | T at +60 s (°C) |\n|---|---|---|---|---|\n| 1 | 29.2 | 12 | 29.0 | 28.8 |\n| 2 | 29.4 | 11 | 29.2 | 29.0 |','| Pratybų bandymas | Pirma nusistovėjusi T (°C) | Delsa (s) | T po +30 s (°C) | T po +60 s (°C) |\n|---|---|---|---|---|\n| 1 | 29,2 | 12 | 29,0 | 28,8 |\n| 2 | 29,4 | 11 | 29,2 | 29,0 |')+'\n\n'+
 example(t('Example 3 · Practice trial 1','3 pavyzdys · 1 pratybų bandymas'),[t('Cool gain: $Q_c=0.100\\times4200\\times(29.2-20.0)=3864\\ \\mathrm{J}$.','Vėsaus gautas kiekis: $Q_c=0{,}100\\times4200\\times(29{,}2-20{,}0)=3864\\ \\mathrm{J}$.'),t('Warm loss magnitude: $Q_w=0.100\\times4200\\times(40.0-29.2)=4536\\ \\mathrm{J}$.','Šilto atiduotas modulis: $Q_w=0{,}100\\times4200\\times(40{,}0-29{,}2)=4536\\ \\mathrm{J}$.'),t('R = 4536 − 3864 = 672 J. This is a water-only mismatch; other recipients and measurement effects remain to be assessed.','R = 4536 − 3864 = 672 J. Tai vien vandens neatitikimas; kitus gavėjus ir matavimo ypatumus dar reikia įvertinti.')],1)))
 b.append(block('check',t('Analyse practice trial 2','Išanalizuok 2 pratybų bandymą'),
 quantity('c1',t('Find the ideal equal-mass final temperature.','Rask idealią vienodų masių galutinę temperatūrą.'),303.15,'absolute-temperature','°C|K',t('30 °C = 303.15 K','30 °C = 303,15 K'),t('(20 + 40)/2 = 30 °C.','(20 + 40)/2 = 30 °C.'),o[0])+
 quantity('c2',t('Practice trial 2 ends at 29.4 °C. Find cool-water heat received.','2 pratybų bandymo galutinė temperatūra 29,4 °C. Rask vėsaus vandens gautą šilumos kiekį.'),3948,'energy-transfer','J|kJ','3948 J',t('0.100 × 4200 × (29.4 − 20.0) = 3948 J.','0,100 × 4200 × (29,4 − 20,0) = 3948 J.'),o[1])+
 quantity('c3',t('Find the **positive magnitude** given away by warm water in practice trial 2.','Rask šilto vandens atiduoto šilumos kiekio **teigiamą modulį** 2 pratybų bandyme.'),4452,'energy-transfer','J|kJ','4452 J',t('0.100 × 4200 × (40.0 − 29.4) = 4452 J. Signed Q to warm water would be −4452 J.','0,100 × 4200 × (40,0 − 29,4) = 4452 J. Q šiltam vandeniui su ženklu būtų −4452 J.'),o[1],wrong=[('-4452',t('That is signed Q to warm water; this asks for the positive magnitude.','Tai Q šiltam vandeniui su ženklu; klausiama teigiamo modulio.'))])+
 quantity('c4',t('Calculate water-only residual R = warm loss − cool gain.','Apskaičiuok vien vandens liekaną R = šilto atiduotas − vėsaus gautas.'),504,'energy-transfer','J|kJ','504 J',t('4452 − 3948 = 504 J.','4452 − 3948 = 504 J.'),o[2])+
 choice('c5',t('What conclusion is justified by the residual?','Kokią išvadą pagrindžia liekana?'),[(t('The water-only estimates differ; investigate omitted energy changes and measurement effects.','Vien vandens įverčiai skiriasi; tirti neįtrauktus energijos pokyčius ir matavimo ypatumus.'),True,t('This diagnoses a model mismatch, not a failure of conservation.','Tai modelio neatitikimas, ne tvermės pažeidimas.')),(t('Exactly 504 J vanished.','Tiksliai 504 J išnyko.'),False,t('The boundary omits the container, thermometer and surroundings.','Riba neįtraukia indo, termometro ir aplinkos.')),(t('Exactly 504 J was transferred to the room.','Tiksliai 504 J perduota kambariui.'),False,t('The residual alone cannot separate the cup’s gain, environmental exchange and measurement effects.','Vien liekana neatskiria indo pokyčio, mainų su aplinka ir matavimo ypatumų.'))],t('Report the residual and its limits. A later cooling trend is context, not an exact allocation of this residual.','Pateik liekaną ir jos ribas. Vėlesnis vėsimas yra aplinkybė, ne tikslus liekanos paskirstymas.'),o[2])+
 task('c6',t('Write a conclusion using your real record or the labelled synthetic set. Include prediction, result, residual, two limitations and one specific improvement. State which data source you used.','Pagal tikrą užrašą arba pažymėtą sintetinį rinkinį parašyk išvadą: prognozė, rezultatas, liekana, dvi ribos ir konkretus patobulinimas. Nurodyk duomenų šaltinį.'),[t('Identify real or synthetic data and the prediction.','Nurodyti tikri ar sintetiniai duomenys ir prognozė.'),t('Use actual inputs and final reading consistently.','Nuosekliai naudoti pradiniai dydžiai ir galutinis rodmuo.'),t('Calculate and interpret the residual with a stated sign convention.','Apskaičiuota ir paaiškinta liekana, nurodžius ženklų sutartį.'),t('Name two plausible limitations without an exact unmeasured loss claim.','Nurodytos dvi pagrįstos ribos, neteigiant tikslaus neišmatuoto nuostolio.'),t('Link an improvement to a limitation.','Patobulinimas susietas su riba.')],t('For synthetic trial 2: ideal prediction 30 °C; illustrative first stable reading 29.4 °C after an 11 s delay. Cool gain 3948 J, warm loss 4452 J, residual 504 J. Container energy changes and thermometer response/timing can matter. A consistent shorter documented delay and a characterised container could improve comparison. These synthetic values demonstrate analysis; they are not evidence that a physical trial succeeded.','2 sintetiniam bandymui: ideali prognozė 30 °C; iliustracinis pirmas nusistovėjęs rodmuo 29,4 °C po 11 s delsos. Vėsaus gauta 3948 J, šilto atiduota 4452 J, liekana 504 J. Svarbūs gali būti indo energijos pokytis ir termometro atsakas bei laikas. Nuosekli trumpesnė dokumentuota delsa ir įvertintas indas gali pagerinti palyginimą. Sintetiniai skaičiai demonstruoja analizę; jie neįrodo sėkmingo fizinio bandymo.'),o[2])))
 b[-1]=b[-1].replace('\n\n</Block>', '\n\n'+
 numeric('c7',t('Optional sensitivity check: both water masses are 0.100 kg. If the final reading increases by 0.1 °C, by how many joules does R = Qwarm − Qcool decrease?','Papildoma jautrumo patikra: abi vandens masės po 0,100 kg. Galutiniam rodmeniui padidėjus 0,1 °C, keliais džauliais sumažėja R = šilto atiduotas − vėsaus gautas?'),'84',t('Both estimates change: 2 × 0.100 × 4200 × 0.1 = 84 J. A 1 °C step changes R by 840 J. This is sensitivity to one reading, not a complete uncertainty bound.','Kinta abu įverčiai: 2 × 0,100 × 4200 × 0,1 = 84 J. 1 °C žingsnis pakeičia R 840 J. Tai jautrumas vienam rodmeniui, ne visas paklaidos įvertis.'),o[2],unit='J')+'\n\n</Block>')
 b.append(block('summary',t('Balance, boundary, evidence','Balansas, riba, įrodymai'),t('The midpoint needs equal masses of the same material and an ideal balance. Otherwise use the mass-weighted formula. Calculate both water changes with one stated sign convention. A residual asks you to check the boundary and assumptions; it does not show energy vanished. Keep real evidence separate from synthetic practice.','Viduriui reikia vienodų tos pačios medžiagos masių ir idealaus balanso. Kitu atveju taikyk mase svertą formulę. Abiejų dalių pokyčius skaičiuok pagal vieną nurodytą ženklų sutartį. Liekana skatina tikrinti ribą ir prielaidas; ji nerodo, kad energija išnyko. Skirk tikrus įrodymus ir sintetines pratybas.')+'\n\n<Next>'+t('What changes when energy enters but temperature does not rise? The next planned lesson studies melting and freezing.','Kas keičiasi, kai energija perduodama, o temperatūra nekyla? Kita planuojama pamoka – lydymasis ir kietėjimas.')+'</Next>'))
 b.append(block('teacher',t('Discuss the model before a verdict','Prieš vertinimą aptark modelį'),t('**45-minute route:** recall 4 min; prediction and boundary 5; balance frames 10; unequal-mass model 5; worked calculations 8; checks 8; conclusion 5. The reversed-mass extension can be follow-up. Timing is untested.\n\nUse the first stable reading consistently, with actual masses and both initial temperatures. A residual rounded to a joule is arithmetic for this practice set, not a claim of one-joule experimental precision. Discuss instrument resolution before interpreting small differences.\n\nSynthetic keys: trial 1 — 3864 J gain, 4536 J loss magnitude, 672 J residual; trial 2 — 3948 J gain, 4452 J loss magnitude, 504 J residual. Ideal equal-mass T = 30 °C; twice as much warm water gives 33.3 °C; twice as much cool water gives 26.7 °C.\n\n**Terms EN · LT:** heat balance · šilumos balansas; weighted mean · svertinis vidurkis; residual · liekana; model assumption · modelio prielaida. Do not label the residual “environmental loss” without accounting for other influences.\n\nWritten work requires comparison with the rubric by a pupil or teacher. Automated quantity checks cannot certify reasoning. Human physics/classroom review remains pending. The four lessons do not complete the whole thermal programme node.','**45 min eiga:** prisiminimas 4 min; prognozė ir riba 5; balanso aiškinimas 10; nevienodų masių modelis 5; skaičiavimai 8; pasitikrinimas 8; išvada 5. Atvirkštinių masių pavyzdys gali būti papildomas. Laikas neišbandytas.\n\nNuosekliai naudokite pirmą nusistovėjusį rodmenį, tikras mases ir abi pradines temperatūras. Iki džaulio pateikta liekana yra šių pratybų aritmetika, ne vieno džaulio eksperimentinio tikslumo teiginys. Prieš aiškindami mažus skirtumus aptarkite prietaisų padalos vertes.\n\nSintetiniai atsakymai: 1 bandymas – gauta 3864 J, atiduota 4536 J, liekana 672 J; 2 bandymas – gauta 3948 J, atiduota 4452 J, liekana 504 J. Ideali vienodų masių T = 30 °C; dvigubai daugiau šilto vandens duoda 33,3 °C; dvigubai daugiau vėsaus – 26,7 °C.\n\n**Terminai EN · LT:** heat balance · šilumos balansas; weighted mean · svertinis vidurkis; residual · liekana; model assumption · modelio prielaida. Liekana nevadinama „nuostoliu aplinkai“, neįvertinus kitų veiksnių.\n\nRašytinį darbą su kriterijais lygina mokinys ar mokytojas. Automatinė dydžio patikra nepatvirtina samprotavimo. Žmogaus fizikos ir darbo klasėje peržiūra dar neatlikta. Keturios pamokos neužbaigia visos šiluminių reiškinių programos temos.')))
 return ''.join(b)

for lang in ['en','lt']:
 for number,fn in enumerate([lesson1,lesson2,lesson3,lesson4],1):
  goal=' '.join(lt if lang=='lt' else en for en,lt in objectives[number-1])
  meta={'title':t(*titles[number-1]),'description':goal,'sidebar':{'order':number},'lesson':{'grade':9,'unit':'thermal','course':['core'],'curriculum':['lt-physics-g9-01'] if number==1 else ['lt-physics-g9-02'],'contentArea':'thermal','achievements':['B1','D1','E1'],'levels':[1,2,3],'exam':[],'minutes':45,'goal':goal,'kicker':t('An original trial lesson. Practising teacher review is still pending.','Originali bandomoji pamoka. Praktikuojančio mokytojo peržiūra dar neatlikta.')}}
  body='---\n'+yaml.safe_dump(meta,sort_keys=False,allow_unicode=True,width=110)+'---\n'
  imports=['Lesson','Block','Frames','Frame','Choice','Option','Why','Ok','Numeric','Quantity','Task','Marks','Mark','Hints','Hint','Solution','Example','ExStep','YourTurn','Next']
  rel='../../../../../' if lang=='lt' else '../../../../'
  body+='import { '+', '.join(imports)+' } from \''+rel+'components/lesson\';\n\n<Lesson>\n\n'+fn()+'\n</Lesson>\n'
  for tag in ['Block','Choice','Numeric','Quantity','Example','YourTurn','Task','Frames','Frame','Solution','ExStep','Marks']:
   body=body.replace('<'+tag+' ', '\n\n<'+tag+' ').replace('<'+tag+'>', '\n\n<'+tag+'>').replace('</'+tag+'>', '</'+tag+'>\n\n')
  file=P/('lt/9/thermal' if lang=='lt' else '9/thermal')/(slugs[number-1]+'.mdx');file.parent.mkdir(parents=True,exist_ok=True);file.write_text(body)
root={'id':'g8.measure','item':'prior-measurement-skills','quote':'Editorial prerequisite; not a verbatim programme quote.','en':'Read a thermometer, convert g to kg and subtract two readings.','lt':'Skaityti termometro rodmenis, perskaičiuoti g į kg ir atimti du rodmenis.','refresh':'Mass conversion and temperature difference','refreshLt':'Masės perskaičiavimas ir temperatūros skirtumas'}
outs=[];ls=[]
for i,group in enumerate(objectives):
 ids=[]
 for j,(en,lt) in enumerate(group):
  ident=f'g9.thermal.{i*3+j+1}';ids.append(ident);needs=['g8.measure'] if i==0 else [f'g9.thermal.{(i-1)*3+1}'];outs.append({'id':ident,'item':'lt-physics-g9-01' if i==0 else 'lt-physics-g9-02','quote':'Editorial objective; see the linked official programme scope.','achievement':['B1','D1','E1'],'level':1,'needs':needs,'en':en,'lt':lt})
 ls.append({'id':f'g9-thermal-0{i+1}','outcomes':ids})
f=Path('src/content/outcomes/grade9.yaml');f.parent.mkdir(parents=True,exist_ok=True);f.write_text(yaml.safe_dump({'programme':'https://emokykla.lt/bendrosios-programos/visos-bendrosios-programos/12','semester':'autumn','roots':[root],'outcomes':outs,'lessons':ls},allow_unicode=True,sort_keys=False,width=110))
print('Wrote four matched English/Lithuanian lessons and 12 outcome records.')
